
INSERT INTO RATINGS (RATING_ID, NAME)
SELECT 1, 'G' WHERE NOT EXISTS (SELECT 1 FROM RATINGS WHERE RATING_ID = 1);

INSERT INTO ratings (RATING_ID, NAME)
SELECT 2, 'PG' WHERE NOT EXISTS (SELECT 1 FROM RATINGS WHERE RATING_ID = 2);

INSERT INTO ratings (RATING_ID, NAME)
SELECT 3, 'PG-13' WHERE NOT EXISTS (SELECT 1 FROM RATINGS WHERE RATING_ID = 3);

INSERT INTO RATINGS (RATING_ID, NAME)
SELECT 4, 'R' WHERE NOT EXISTS (SELECT 1 FROM RATINGS WHERE RATING_ID = 4);

INSERT INTO RATINGS (RATING_ID, NAME)
SELECT 5, 'NC-17' WHERE NOT EXISTS (SELECT 1 FROM RATINGS WHERE RATING_ID = 5);



INSERT INTO GENRES (GENRE_ID, NAME)
SELECT 1, 'Комедия' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GENRE_ID = 1);

INSERT INTO GENRES (GENRE_ID, NAME)
SELECT 2, 'Драма' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GENRE_ID = 2);

INSERT INTO GENRES (GENRE_ID, NAME)
SELECT 3, 'Мультфильм' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GENRE_ID = 3);

INSERT INTO GENRES (GENRE_ID, NAME)
SELECT 4, 'Триллер' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GENRE_ID = 4);

INSERT INTO GENRES (GENRE_ID, NAME)
SELECT 5, 'Документальный' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GENRE_ID = 5);

INSERT INTO GENRES (GENRE_ID, NAME)
SELECT 6, 'Боевик' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GENRE_ID = 6);